---
- name: Install nginx package dependencies
  ansible.builtin.package:
    name: '{{ nginx_packages }}'
    state: present
  become: true
  register: install_nginx_packages
  when: nginx_packages is defined
  tags:
    - install

- name: install dependencies pip
  become: True
  pip:
    name: '{{ nginx_pip_modules }}'
  when: nginx_pip_modules is defined
  tags:
    - install
