---
# task for equipindustry.nginx

- name: Ensure nginx_vhost_path exists.
  become: yes
  file:
    path: '{{ _nginx_vhost_path }}'
    state: directory
  notify: reload nginx

- name: Add managed vhost config file (if any vhosts are configured).
  become: yes
  template:
    src: default.conf.j2
    dest: '{{ _nginx_vhost_path }}/{{ nginx_vhosts_filename }}'
    mode: 0644
  when: nginx_vhosts|length > 0
  notify: reload nginx

- name: Remove managed vhost config file (if no vhosts are configured).
  become: yes
  file:
    path: '{{ _nginx_vhost_path }}/{{ nginx_vhosts_filename }}'
    state: absent
  when: nginx_vhosts|length == 0
  notify: reload nginx

# Nginx setup.
- name: Copy nginx configuration in place.
  become: yes
  template:
    src: nginx.conf.j2
    dest: '{{ _nginx_conf_file_path }}'
    owner: root
    group: '{{ _root_group }}'
    mode: 0644
  notify:
    - reload nginx
