---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: hadenlabs.nginx

  vars:
    user: 'ubuntu'
    nginx_only_deploy: no
    # active conf nginx
    nginx_gzip: yes
    # security
    nginx_add_security_header: yes
