---
dependency:
  name: galaxy
driver:
  name: ec2
  region: us-east-2
platforms:
  - name: molecule-instance
    instance_type: t2.micro
    image_owner: 099720109477
    image_name: 'ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-*'
    image_architecture: 'x86_64'

provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: 'true'
  options:
    v: true
  config_options:
    defaults:
      interpreter_python: /usr/bin/python3
verifier:
  name: testinfra
  options:
    verbose: true
    sudo: true
